#!/bin/sh



mount_ubuntu() 

{
  #unmount  /compat/linux/proc if mounted
       
      
      if ! [ -z "$(mount | grep linprocfs)" ]; then 
       
           doas   umount  /compat/linux/proc

      fi
                 
           
    if  [ -z "$(mount | grep nullfs )" ]; then 
       
       doas mount -t nullfs /compat/ubuntu/ /compat/linux/

    fi


    if  [ -z "$(mount | grep linprocfs)" ]; then 
       
       doas mount -t linprocfs linproc /compat/linux/proc

    fi

      
    

   if  [ -z "$(mount | grep tmpfs)" ]; then
       
  
     doas mount -t tmpfs tmpfs /compat/linux/dev/shm
                       
   fi



    if  [ -z "$(mount | grep linsysfs)" ]; then
       
       doas mount -t linsysfs linsys /compat/linux/sys
                       
   fi


       doas chmod 1777 /compat/linux/dev/shm
    
 } 


          

umount () 
  {    
       doas umount -f  /compat/linux/proc
       doas umount -f  /compat/linux/dev/shm
       doas umount -f  /compat/linux/sys
       doas umount -f  /compat/linux  

      if  [  -z "$(mount | grep linprocfs )" ]; then
          doas mount -t linprocfs linproc /compat/linux/proc
          doas mount -t tmpfs tmpfs /compat/linux/dev/shm
          doas chmod 1777 /compat/linux/dev/shm
          doas mount -t linsysfs linsys /compat/linux/sys
          
     
      fi
  }

  
case $1 in 
   -m) 
   mount_ubuntu 
       ;; 
   -u) 
     umount 
      ;; 
   
esac 



     